#cloud-config
autoinstall:
  version: 1
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  identity:
    hostname: ubuntu-desktop
    username: administrador
    password: "$6$u9w11mcDgLFTY1k0$jKePXcb6Etztl08oakzYFk6Wve3dOkVW1bFeNrKfddDSMs6bOJMu7lgpImWfzkTSmwB7hQM8LQPCEMWDPWAA71"
  timezone: America/Sao_Paulo
  storage:
    layout:
      name: direct
    erase: true
    use-lvm: true
  packages:
    - flatpak
    - snapd
    - gnome-software
    - gnome-software-plugin-flatpak
    - gnome-software-plugin-snap
    - apt-transport-https
    - software-properties-common
    - curl
    - wget
    - preload
    - zram-tools 
    - ufw
    - gufw
    - openssh-server
    - language-selector-common
    - language-pack-pt
    - language-pack-gnome-pt
    - language-pack-pt-base
    - language-pack-gnome-pt-base
    - libreoffice
    - libreoffice-l10n-pt-br
    - libreoffice-help-pt-br
    - ttf-mscorefonts-installer
    - fonts-crosextra-carlito
    - fonts-crosextra-caladea
    - fonts-liberation
    - fonts-noto
    - fonts-noto-color-emoji
    - fonts-dejavu
    - fonts-freefont-ttf
    - fonts-noto-mono
    - fonts-noto-ui-core
    - thunderbird
    - thunderbird-locale-pt-br
    - gzip
    - bzip2
    - xz-utils
    - tar
    - arc
    - lzop
    - cpio
    - lzma
    - p7zip-full
    - 7zip-rar
    - zip
    - unzip
    - rar
    - unrar
    - ubuntu-restricted-extras
    - ubuntu-restricted-addons
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-libav
    - totem
    - totem-common
    - totem-plugins
    - dconf-cli
    - gnome-extensions-app
    - mesa-utils
    - mesa-vulkan-drivers
    - vulkan-tools
  snaps:
    - name: firefox
    - name: thunderbird
    - name: gnome-weather
    - name: onlyoffice-desktopeditors
  late-commands:
    - curtin in-target -- bash -c "echo 'LANG=pt_BR.UTF-8' > /etc/default/locale"
    - curtin in-target -- apt update && apt full-upgrade -y
    - curtin in-target -- snap refresh
    - curtin in-target -- apt purge -y apport whoopsie ubuntu-report
    - curtin in-target -- apt autoremove -y
    - curtin in-target -- systemctl disable apport.service
    - curtin in-target -- systemctl stop apport.service
    - curtin in-target -- systemctl disable whoopsie.service
    - curtin in-target -- systemctl stop whoopsie.service
    - curtin in-target -- rm -rf /etc/ubuntu-report
    - curtin in-target -- rm -rf /var/lib/ubuntu-report
    - curtin in-target -- ufw default deny incoming
    - curtin in-target -- ufw default allow outgoing
    - curtin in-target -- ufw allow ssh
    - curtin in-target -- ufw allow 3389/tcp
    - curtin in-target -- ufw allow 3389/udp
    - curtin in-target -- ufw logging on
    - curtin in-target -- ufw --force enable
    - curtin in-target -- apt purge -y vino vnc4server tightvncserver remmina* || true
    - curtin in-target -- flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - curtin in-target -- snap remove snap-store || true
    - curtin in-target -- mkdir -p /etc/dconf/db/local.d
    - curtin in-target -- bash -c 'cat <<EOF > /etc/dconf/db/local.d/00-ubuntu-settings
[org/gnome/shell/extensions/dash-to-dock]
show-apps-at-top=true
dock-position="BOTTOM"
click-action="minimize"
background-opacity=0.8
dash-to-dock-alignment="CENTER"
panel-mode=true
extend-height=true
autohide=false
dash-max-icon-size=32

[org/gnome/shell/extensions/ding]
show-home=true
show-trash=true
show-mount=true
show-volumes=true
show-link-emblem=true

[org/gnome/shell]
favorite-apps=["onlyoffice-desktopeditors.desktop", "firefox.desktop", "thunderbird.desktop", "google-chrome.desktop"]

[org/gnome/totem/plugins]
enabled=["cdrom", "dvd", "vcd", "audio", "video"]

[org/gnome/weather]
location="Rio de Janeiro"
EOF'
    - curtin in-target -- mkdir -p /home/administrador/.config/dconf
    - curtin in-target -- bash -c 'cat <<EOF > /home/administrador/.config/dconf/user-profile.ini
[org/gnome/shell/extensions/dash-to-dock]
show-apps-at-top=true
dock-position="BOTTOM"
click-action="minimize"
background-opacity=0.8
dash-to-dock-alignment="CENTER"
panel-mode=true
extend-height=true
autohide=false
dash-max-icon-size=32

[org/gnome/shell/extensions/ding]
show-home=true
show-trash=true
show-mount=true
show-volumes=true
show-link-emblem=true

[org/gnome/shell]
favorite-apps=["onlyoffice-desktopeditors.desktop", "firefox.desktop", "thunderbird.desktop", "google-chrome.desktop"]

[org/gnome/weather]
location="Rio de Janeiro"

[org/gnome/totem/plugins]
enabled=["cdrom", "dvd", "vcd", "audio", "video"]
EOF'
    - curtin in-target -- chown administrador:administrador /home/administrador/.config/dconf/user-profile.ini
    - curtin in-target -- bash -c "sudo -u administrador dconf load / < /home/administrador/.config/dconf/user-profile.ini"
    - curtin in-target -- mkdir -p /home/administrador/.config
    - curtin in-target -- bash -c 'cat <<EOF > /home/administrador/.config/mimeapps.list
[Default Applications]
video/mp4=totem.desktop
video/x-matroska=totem.desktop
video/x-msvideo=totem.desktop
video/quicktime=totem.desktop
video/x-flv=totem.desktop
video/webm=totem.desktop
video/x-ms-wmv=totem.desktop
audio/mpeg=totem.desktop
audio/x-wav=totem.desktop
audio/ogg=totem.desktop
audio/x-flac=totem.desktop
audio/mp3=totem.desktop
audio/x-aac=totem.desktop
audio/vnd.rn-realaudio=totem.desktop
x-scheme-handler/mailto=thunderbird.desktop
EOF'
    - curtin in-target -- chown administrador:administrador /home/administrador/.config/mimeapps.list
    - curtin in-target -- dconf update
    - curtin in-target -- bash -c 'echo -e "[Default Applications]\nvideo/mp4=totem.desktop\nvideo/x-matroska=totem.desktop\nvideo/x-msvideo=totem.desktop\nvideo/quicktime=totem.desktop\nvideo/x-flv=totem.desktop\nvideo/webm=totem.desktop\nvideo/x-ms-wmv=totem.desktop\naudio/mpeg=totem.desktop\naudio/x-wav=totem.desktop\naudio/ogg=totem.desktop\naudio/x-flac=totem.desktop\naudio/mp3=totem.desktop\naudio/x-aac=totem.desktop\naudio/vnd.rn-realaudio=totem.desktop" >> /target/usr/share/applications/mimeapps.list'
    - curtin in-target -- bash -c 'wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -'
    - curtin in-target -- bash -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get install -y google-chrome-stable
    - curtin in-target -- systemctl enable preload
    - curtin in-target -- systemctl enable zramswap.service || true
