#cloud-config
autoinstall:
  version: 1
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  identity:
    hostname: ubuntu-desktop
    username: administrador
    password: "$6$u9w11mcDgLFTY1k0$jKePXcb6Etztl08oakzYFk6Wve3dOkVW1bFeNrKfddDSMs6bOJMu7lgpImWfzkTSmwB7hQM8LQPCEMWDPWAA71"
  timezone: America/Sao_Paulo
  storage:
    layout:
      name: direct
    erase: true
    use-lvm: false
  packages:
    - flatpak
    - snapd
    - gnome-software
    - gnome-software-plugin-flatpak
    - gnome-software-plugin-snap
    - apt-transport-https
    - software-properties-common
    - curl
    - wget
    - preload
    - zram-tools 
    - ufw
    - gufw
    - openssh-server
    - language-selector-common
    - language-pack-pt
    - language-pack-pt-base
    - language-pack-gnome-pt
    - language-pack-gnome-pt-base
    - libreoffice
    - libreoffice-l10n-pt-br
    - libreoffice-l10n-pt
    - libreoffice-help-pt-br
    - libreoffice-help-pt
    - hunspell-pt-br
    - hunspell-pt-pt
    - hyphen-pt-br
    - hyphen-pt-pt
    - mythes-pt-br
    - mythes-pt-pt
    - aspell-pt-br
    - wbrazilian
    - ttf-mscorefonts-installer
    - fonts-crosextra-carlito
    - fonts-crosextra-caladea
    - fonts-liberation
    - fonts-noto
    - fonts-noto-color-emoji
    - fonts-dejavu
    - fonts-freefont-ttf
    - fonts-noto-mono
    - fonts-noto-ui-core
    - thunderbird
    - thunderbird-locale-pt-br
    - thunderbird-locale-pt
    - thunderbird-locale-pt-pt
    - gzip
    - bzip2
    - xz-utils
    - tar
    - arc
    - lzop
    - cpio
    - lzma
    - p7zip-full
    - 7zip-rar
    - zip
    - unzip
    - rar
    - unrar
    - ubuntu-restricted-extras
    - ubuntu-restricted-addons
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-libav
    - libavcodec-extra
    - totem
    - totem-common
    - totem-plugins
    - dconf-cli
    - gnome-extensions-app
    - linux-firmware
    - mesa-utils
    - mesa-vulkan-drivers
    - vulkan-tools
    - apparmor
    - apparmor-profiles
    - apparmor-utils
    - clamav
    - clamav-daemon
    - clamtk
    - fail2ban
  snaps:
    - name: snap-store
    - name: firefox
    - name: thunderbird
    - name: onlyoffice-desktopeditors
    - name: cheese
    - name: gnome-weather
  late-commands:
    - curtin in-target -- timedatectl set-timezone "America/Sao_Paulo"
    - curtin in-target -- timedatectl set-ntp true
    - curtin in-target -- bash -c "echo 'LANG=pt_BR.UTF-8' > /etc/default/locale"
    - curtin in-target -- apt-get update && apt-get upgrade -y
    - curtin in-target -- snap refresh
    - curtin in-target -- ubuntu-drivers install
    - curtin in-target -- apt-get --purge autoremove ubuntu-report popularity-contest apport apport-symptoms whoopsie kerneloops kerneloops-applet -y || true
    - curtin in-target -- apt-get --purge autoremove -y
    - curtin in-target -- systemctl disable apport.service || true
    - curtin in-target -- systemctl disable whoopsie.service || true
    - curtin in-target -- systemctl disable ModemManager.service || true
    - curtin in-target -- systemctl disable avahi-daemon || true
    - curtin in-target -- rm -rf /etc/ubuntu-report
    - curtin in-target -- rm -rf /var/lib/ubuntu-report
    - curtin in-target -- ufw default deny incoming
    - curtin in-target -- ufw default allow outgoing
    - curtin in-target -- ufw allow ssh
    - curtin in-target -- ufw allow 3389/tcp
    - curtin in-target -- ufw allow 3389/udp
    - curtin in-target -- ufw logging on
    - curtin in-target -- ufw --force enable
    - curtin in-target -- apt-get --purge autoremove vino xrdp vnc4server tightvncserver remmina* modemmanager -y || true
    - curtin in-target -- flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - curtin in-target -- wget -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - curtin in-target -- dpkg -i /tmp/google-chrome.deb || true
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get install -f -y || true
    - curtin in-target -- sysctl -w kernel.randomize_va_space=2
    - curtin in-target -- sysctl -w fs.suid_dumpable=0
    - curtin in-target -- snap remove snap-store || true
    - curtin in-target -- bash -c "test -f /etc/ssh/sshd_config && sed -i 's/^#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config || echo 'sshd_config not found'"
    - curtin in-target -- systemctl enable apparmor
    - curtin in-target -- systemctl enable clamav-freshclam.service
    - curtin in-target -- systemctl enable clamav-daemon.service
    - curtin in-target -- systemctl enable fail2ban.service
    - curtin in-target -- systemctl enable zramswap.service
    - curtin in-target -- bash -c 'echo "0 11 * * * /usr/bin/freshclam --quiet" >> /etc/crontab'
    - curtin in-target -- bash -c 'echo "0 12 * * 2,4 /usr/bin/clamscan -r /home" >> /etc/crontab'
