#cloud-config
autoinstall:
  version: 1
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  identity:
    hostname: ubuntu-desktop
    username: administrador
    password: "$6$u9w11mcDgLFTY1k0$jKePXcb6Etztl08oakzYFk6Wve3dOkVW1bFeNrKfddDSMs6bOJMu7lgpImWfzkTSmwB7hQM8LQPCEMWDPWAA71"
  timezone: America/Sao_Paulo
  storage:
    layout:
      name: direct
    erase: true
    use-lvm: false
  packages:
    - flatpak
    - snapd
    - gnome-software
    - gnome-software-plugin-flatpak
    - gnome-software-plugin-snap
    - apt-transport-https
    - software-properties-common
    - curl
    - wget
    - preload
    - zram-tools
    - gufw
    - ufw
    - openssh-server
    - gnome-remote-desktop
    - language-selector-common
    - language-pack-pt
    - language-pack-gnome-pt
    - language-pack-pt-base
    - language-pack-gnome-pt-base
    - libreoffice
    - libreoffice-l10n-pt-br
    - libreoffice-help-pt-br
    - ttf-mscorefonts-installer
    - fonts-crosextra-carlito
    - fonts-crosextra-caladea
    - fonts-liberation
    - fonts-noto
    - fonts-noto-color-emoji
    - fonts-dejavu
    - fonts-freefont-ttf
    - fonts-noto-mono
    - fonts-noto-ui-core
    - thunderbird
    - thunderbird-locale-pt-br
    - gzip
    - bzip2
    - xz-utils
    - tar
    - arc
    - lzop
    - cpio
    - p7zip-full
    - zip
    - unzip
    - rar
    - unrar
    - ubuntu-restricted-addons
    - ubuntu-restricted-extras
    - totem
    - totem-common
    - totem-plugins
    - dconf-cli
    - gnome-extensions-app
  snaps:
    - name: firefox
    - name: thunderbird
    - name: gnome-weather
    - name: onlyoffice-desktopeditors
  late-commands:
    - curtin in-target -- bash -c "echo 'LANG=pt_BR.UTF-8' > /etc/default/locale"
    - curtin in-target -- apt purge -y apport whoopsie ubuntu-report
    - curtin in-target -- apt autoremove -y
    - curtin in-target -- systemctl disable apport.service
    - curtin in-target -- systemctl stop apport.service
    - curtin in-target -- systemctl disable whoopsie.service
    - curtin in-target -- systemctl stop whoopsie.service
    - curtin in-target -- rm -rf /etc/ubuntu-report
    - curtin in-target -- rm -rf /var/lib/ubuntu-report
    - curtin in-target -- ufw default deny incoming
    - curtin in-target -- ufw default allow outgoing
    - curtin in-target -- ufw allow ssh
    - curtin in-target -- ufw allow 3389/tcp
    - curtin in-target -- ufw allow 3389/udp
    - curtin in-target -- ufw logging on
    - curtin in-target -- ufw --force enable
    - curtin in-target -- apt purge -y vino vnc4server tightvncserver remmina* || true
    - curtin in-target -- flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - curtin in-target -- snap remove snap-store || true
    - curtin in-target -- gsettings set org.gnome.shell.extensions.dash-to-dock show-apps-at-top true
    - curtin in-target -- gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'bottom'
    - curtin in-target -- gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
    - curtin in-target -- gsettings set org.gnome.shell.extensions.dash-to-dock background-opacity 0.8
    - curtin in-target -- gsettings set org.gnome.shell.extensions.dash-to-dock dash-to-dock-alignment 'center'
    - curtin in-target -- gsettings set org.gnome.shell.extensions.dash-to-dock panel-mode true
    - curtin in-target -- gsettings set org.gnome.shell.extensions.dash-to-dock extend-height true
    - curtin in-target -- gsettings set org.gnome.shell.extensions.dash-to-dock autohide false
    - curtin in-target -- gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 32
    - curtin in-target -- gsettings set org.gnome.shell.extensions.ding show-home true
    - curtin in-target -- gsettings set org.gnome.shell.extensions.ding show-trash true
    - curtin in-target -- gsettings set org.gnome.shell.extensions.ding show-mount true
    - curtin in-target -- gsettings set org.gnome.shell.extensions.ding show-volumes true
    - curtin in-target -- gsettings set org.gnome.shell.extensions.ding show-link-emblem true
    - curtin in-target -- bash -c 'gsettings set org.gnome.shell favorite-apps "[\'onlyoffice-desktopeditors.desktop\', \'firefox.desktop\', \'thunderbird.desktop\', \'google-chrome.desktop\']"'
    - curtin in-target -- bash -c 'echo -e "[Default Applications]\nx-scheme-handler/mailto=thunderbird.desktop" >> /usr/share/applications/mimeapps.list'
    - curtin in-target -- gsettings set org.gnome.totem.plugins.enabled "['cdrom', 'dvd', 'vcd', 'audio', 'video']"
    - curtin in-target -- bash -c 'echo -e "[Default Applications]\nvideo/mp4=totem.desktop\nvideo/x-matroska=totem.desktop\nvideo/x-msvideo=totem.desktop\nvideo/quicktime=totem.desktop\nvideo/x-flv=totem.desktop\nvideo/webm=totem.desktop\nvideo/x-ms-wmv=totem.desktop\naudio/mpeg=totem.desktop\naudio/x-wav=totem.desktop\naudio/ogg=totem.desktop\naudio/x-flac=totem.desktop\naudio/mp3=totem.desktop\naudio/x-aac=totem.desktop\naudio/vnd.rn-realaudio=totem.desktop" >> /target/usr/share/applications/mimeapps.list'
    - curtin in-target -- bash -c 'wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -'
    - curtin in-target -- bash -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get install -y google-chrome-stable
    - curtin in-target -- bash -c "gsettings set org.gnome.shell favorite-apps "['onlyoffice-desktopeditors.desktop', 'firefox.desktop', 'thunderbird.desktop', 'google-chrome.desktop']""
    - curtin in-target -- gsettings set org.gnome.weather.location city 'Rio de Janeiro' || true
    - curtin in-target -- systemctl enable preload
    - curtin in-target -- systemctl enable zramswap.service || true
