#cloud-config
autoinstall:
  version: 1
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  identity:
    hostname: ubuntu-desktop
    username: administrador
    password: "$6$u9w11mcDgLFTY1k0$jKePXcb6Etztl08oakzYFk6Wve3dOkVW1bFeNrKfddDSMs6bOJMu7lgpImWfzkTSmwB7hQM8LQPCEMWDPWAA71"
  timezone: America/Sao_Paulo
  storage:
    layout:
      name: direct
    erase: true
    use-lvm: false
  packages:
    - flatpak
    - snapd
    - gnome-software
    - gnome-software-plugin-flatpak
    - gnome-software-plugin-snap
    - apt-transport-https
    - software-properties-common
    - curl
    - wget
    - preload
    - zram-tools 
    - ufw
    - gufw
    - openssh-server
    - language-selector-common
    - language-pack-pt
    - language-pack-pt-base
    - language-pack-gnome-pt
    - language-pack-gnome-pt-base
    - libreoffice
    - libreoffice-l10n-pt-br
    - libreoffice-help-pt-br
    - hunspell-pt-br
    - hyphen-pt-br
    - mythes-pt-br
    - aspell-pt-br
    - ttf-mscorefonts-installer
    - fonts-crosextra-carlito
    - fonts-crosextra-caladea
    - fonts-liberation
    - fonts-noto
    - fonts-noto-color-emoji
    - fonts-dejavu
    - fonts-freefont-ttf
    - fonts-noto-mono
    - fonts-noto-ui-core
    - thunderbird
    - thunderbird-locale-pt-br
    - gzip
    - bzip2
    - xz-utils
    - tar
    - arc
    - lzop
    - cpio
    - lzma
    - p7zip-full
    - 7zip-rar
    - zip
    - unzip
    - rar
    - unrar
    - ubuntu-restricted-extras
    - ubuntu-restricted-addons
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-libav
    - totem
    - totem-common
    - totem-plugins
    - dconf-cli
    - gnome-extensions-app
    - mesa-utils
    - mesa-vulkan-drivers
    - vulkan-tools
  snaps:
    - name: firefox
    - name: thunderbird
    - name: gnome-weather
    - name: onlyoffice-desktopeditors
  late-commands:
    - curtin in-target -- bash -c "echo 'LANG=pt_BR.UTF-8' > /etc/default/locale"
    - curtin in-target -- apt update && apt full-upgrade -y
    - curtin in-target -- snap refresh
    - curtin in-target -- apt purge -y apport whoopsie ubuntu-report
    - curtin in-target -- apt autoremove -y
    - curtin in-target -- systemctl disable apport.service
    - curtin in-target -- systemctl stop apport.service
    - curtin in-target -- systemctl disable whoopsie.service
    - curtin in-target -- systemctl stop whoopsie.service
    - curtin in-target -- rm -rf /etc/ubuntu-report
    - curtin in-target -- rm -rf /var/lib/ubuntu-report
    - curtin in-target -- ufw default deny incoming
    - curtin in-target -- ufw default allow outgoing
    - curtin in-target -- ufw allow ssh
    - curtin in-target -- ufw allow 3389/tcp
    - curtin in-target -- ufw allow 3389/udp
    - curtin in-target -- ufw logging on
    - curtin in-target -- ufw --force enable
    - curtin in-target -- apt purge -y vino vnc4server tightvncserver remmina* || true
    - curtin in-target -- flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - curtin in-target -- snap remove snap-store || true
    - curtin in-target -- bash -c 'wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -'
    - curtin in-target -- bash -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get install -y google-chrome-stable
    - curtin in-target -- systemctl enable preload
    - curtin in-target -- systemctl enable zramswap.service || true
